name: Deploy to Cocoapods
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Cocoapods
      run: gem install cocoapods
    - name: Deploy to Cocoapods
      run: |
        set -eo pipefail
        python ./scripts/build_podspecs.py -u $(git describe --tags `git rev-list --tags --max-count=1`)
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}